### ISSUE TITLE
Emulator doesn't show up

### ISSUE THREAD

**Issue by davidvavra** [Scarygami/mirror-api#11]
Hi,
today I updated source to the latest version and deployed it (without any changes other than client ids etc.) to https://glass-sandbox.appspot.com. But even if I grant the permissions, emulator doesn't appear and G+ sign in button appears again.

I got same behaviour on your https://mirror-api.appspot.com/ so I assume it's not a fault of my configuration.

**Comment by Scarygami** [comment]
Ah yeah, at some point I changed it so that glass-sandbox.appspot.com actually uses the real Mirror API (which you have to have access to, so authentication will fail otherwise.) You can sign-in at https://glass-sandbox.appspot.com/test/ instead which uses the emulated API.

The emulator at https://glass-sandbox.appspot.com/glass/ uses the emulated API as well.

The idea was that people can actually implement their full application in /test/ using the emulated API, and once they have access to the real Mirror API the app would automagically be up and running at the root already with no changes necessary (except maybe a new Client ID with the API enabled).

**Comment by Scarygami** [comment]
Also see my post about this here: https://plus.google.com/112336147904981294875/posts/2qnsNTuzK6e

**Comment by davidvavra** [comment]
My bad, I forgot about that. Thanks for quick answer. I think it's a good structure, you could write some warning on root and /test websites so people woudn't get confused.

**Comment by Scarygami** [comment]
Good idea, will do that :)

(I was confused about it myself several times already...)
