### ISSUE TITLE
Contacts and Subscriptions are not Disconnecting once we signout

### ISSUE THREAD

**Issue by ghost** [Scarygami/mirror-api#12]
The Glass is not disconnecting the contacts and subscriptions once we signout and disconnect. 

in <code>/glass</code>:
<code>Uncaught ReferenceError: disconnectCallback is not defined</code>

In <code>/test</code>:

<pre><code>Error 500: Internal Server Error service.js:162
{"error": {"code": 500, "message": "Failed to refresh access token."}} service.js:164</code></pre>

And BTW, I checked in my localhost and chrome/chromium.

**Comment by Scarygami** [comment]
Can you try to go to `/test/?reconnect=true` sign-in there and then sign-out again? "Failed to refresh access token." errors usually happen when the stored credentials aren't valid. The ?reconnect=true parameter makes sure the complete auth-flow is repeated with fresh credentials.

I'll checkout the error in `/glass`

**Comment by ghost** [comment]
Tried with <code>/test/?reconnect=true</code> but that didn't help. Contact is being added again and again rather than replacing the old. 

And is there a way to reset them manually? May be by resetting the datastore or something like that?

**Comment by ghost** [comment]
Any updates about the previous comment?

**Comment by Scarygami** [comment]
I wasn't able to reproduce the behaviour. When I click on disconnect on the /test/ page, contacts and subscriptions are deleted. Note that disconnection at /glass won't do this since it isn't directly connected to the services, the sign-in button there is only to connect to the mirror API but not to connect to the actual services.

For now the behaviour during connect isn't really the best practice, because I always first delete contacts and subscriptions and then create them new, the reasoning behind this being that with changing stuff around in the background I want to make sure that always only the currently valid contacts and subscription are active.

You can access contacts and subscriptions from appengine.google.com in the Datastore Viewer and delete entries there as well.

**Comment by ghost** [comment]
Okay. I cleared the datastore and also the <code>/test/</code> deletes the contacts and subscriptions but the old timeline items preserves. May be we can clear that too right?

**Comment by Scarygami** [comment]
I decided against deleting timeline items for this test implementation, because I find it easier to test if I already have old items in the timeline without having to create new ones every time.

But of course that's something you can consider implementing for your Glassware. I'm not sure but it might be that the actual Mirror API takes care of this when a user disconnects an app. But items will disappear from the timeline anyway as time passes, because they are not updated and newer items take their place.

**Comment by Scarygami** [comment]
Fixed the error that appears when disconnecting the Glass emulator in https://github.com/Scarygami/mirror-api/commit/1d62bf0843bf3dde9af6625d36dea6e6e1963dee
