### ISSUE TITLE
"Take a Picture" shows a green screen

### ISSUE THREAD

**Issue by ghost** [Scarygami/mirror-api#14]
After I allow the browser to access the camera, a green screen is coming for 3 seconds and the same is being taken as picture. Sometimes camera is not at all working and fails with the following corresponding errors.

<code>NavigatorUserMediaError {code: 1, PERMISSION_DENIED: 1}</code>

Also it seems like only the "Take a Picture" command is recognized and other speech commands are not. Most of the times this error comes.

<code>SpeechRecognitionError {message: "", error: "network", clipboardData: undefined, cancelBubble: false, returnValue: true…}</code>

OS: Ubuntu 12.04 (Though video capture works in Windows)
Cam: Intex IT-305WC
Browser: Chrome/Chromium/Firefox
Host: localhost and appspot

**Comment by Scarygami** [comment]
Both getUserMedia and SpeechRecognition are very experimental features and not fully support across all platforms and browsers yet. I've had similar issues as well on some computers while they work perfectly on others, but I don't think there's anything I can do about this since it's out of my control. 

"Take a picture" is the only supported command at the moment, other commands are not implemented yet.
