### ISSUE TITLE
Issues with appcfg.py

### ISSUE THREAD

**Issue by dhermes** [Scarygami/mirror-api#5]
You mention:

"Alternatively (because the appcfg.py deploy script sometimes doesn't recognize the symlink correctly) copy the folder endpoints-proto-datastore/endpoints_proto_datastore/ over to mirror_api_server so that you get this folder structure:"

in the README.

What sort of issues are you seeing? If there are cases where it doesn't recognize the symlink, then it is a bug in appcfg.py. However, I don't believe this is the case and it seems there may be some usage error that can be rectified/addressed.

Also, it's probably helpful in terms of deploy times/size to add skip_files:

skip_files:
... LIST OF EXISTING ...
- ^(._/)?endpoints-proto-datastore/endpoints_proto_datastore/._$

REF: https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files

**Comment by Scarygami** [comment]
Several people who tried contacted me about problems with the API not being available after deploying, which turned out to be because the endpoints_proto_datastore was missing, even though they were sure to have set everything up correctly. It's working correctly with the symlink for me, so I added this extra part in the readme in case people can't get the symlink to work (for whatever reason). I will re-phrase that sentence, because it's most likely not an appcfg.py issue.

**Comment by Scarygami** [comment]
@financeCoding I think you were having issues with this as well, could you maybe try to see if you can pin-point the issue?

**Comment by adam-singer** [comment]
@Scarygami I'm on OSX so maybe that was the issue, but if I just copied the library in to the folder where it was symlinked then there was no issue. Maybe just setup the submodule in that directory instead of the directory above?

**Comment by dhermes** [comment]
Yeah I read the issue @financeCoding was having but it's very possible the issue was with the symlink, not the appcfg.py code.

It'd be great to have something reproducible, like a series of commands starting with a fresh checkout and then maybe some "ln -s <symlink>" output for debugging purposes.

**Comment by adam-singer** [comment]
Is it normal practice with appengine to symlink python modules into your project? If not I dont see why one does not move the module into the project like the rest of the modules?

**Comment by dhermes** [comment]
1) Yes it is normal practice.

2) The reason is that we want to keep up to date via the submodule. But git submodules require adding the whole project, while the actual library lives under the project as the endpoints_proto_datastore.

An alternative to using a symlink would be mangling the import path in appengine_config.py as is done for third party in the Rietveld project:
https://code.google.com/p/rietveld/source/browse/appengine_config.py?r=24cb72fc0aa94c648a66593d1919ee0160dad570#50

**Comment by adam-singer** [comment]
Maybe I'm not understanding this, but why not move the submodule under the `mirror_api_server` directory and avoid the symlink business altogether? You should be able todo `git submodule add https://code.google.com/p/endpoints-proto-datastore mirror_api_server/endpoints-proto-datastore`. Then your `.gitmodules` will look like 

```
[submodule "endpoints-proto-datastore"]
    path = mirror_api_server/endpoints-proto-datastore
    url = https://code.google.com/p/endpoints-proto-datastore/
```

instead of 

```
[submodule "endpoints-proto-datastore"]
    path = endpoints-proto-datastore
    url = https://code.google.com/p/endpoints-proto-datastore/
```

**Comment by dhermes** [comment]
The issue is that mirror_api_server/endpoints-proto-datastore is not where the library would be, it would be in

mirror_api_server/endpoints-proto-datastore/endpoints_proto_datastore

and since 

mirror_api_server/endpoints-proto-datastore

doesn't have an _ _ init _ _.py file in it (and has - characters, which is a Python no-no for modules/packages) you can't import anything that lives under mirror_api_server/endpoints-proto-datastore.

Hence the import path mangling.

**Comment by adam-singer** [comment]
ok, now I get why it cant be moved into that directory via submodule. I'm not an appengine expert but something about using the symlink and expecting appcfg to pick it up is bugging me. Wondering if it has todo with `ln` on mac being part of the bsd family of tools instead of the gnu like linux. Another option is to `rsync` the module instead of `ln` but that would need to be done after every update.

**Comment by adam-singer** [comment]
Just tried to reproduce this with no luck.

**Comment by dhermes** [comment]
Yeah it should "just work" and like I said I'd love to see 

"Alternatively (because the appcfg.py deploy script sometimes doesn't recognize the symlink correctly) copy the folder endpoints-proto-datastore/endpoints_proto_datastore/ over to mirror_api_server so that you get this folder structure:"

removed from the README unless it can actually be reproduced.

This whole symlink mess can still be resolved if we want to add an appengine_config.py.

**Comment by Scarygami** [comment]
I've rephrased the sentence for now (to remove the wrong blame on appcfg.py) https://github.com/Scarygami/mirror-api/commit/9f5d71375dff7a43e51b1be373ffd61856e77c01

Will see if I can get some of the other people who reported their problems with the setup privately, to try and reproduce it.

**Comment by dhermes** [comment]
Thanks for that. (Sorry for accidentally closing the issue, I tabbed onto the "Close & Comment" button without realizing.)

I guess we can close this issue now and re-open if/when you hear back.

What are your thoughts on adding to sys.path via appengine_config.py as discussed above?

**Comment by Scarygami** [comment]
I actually quite like the way this is handled now. Going to keep it and see how people are able to handle it.

Thanks for your feedback, as always :)

**Comment by dhermes** [comment]
Sure thing.
